# -*- coding: utf-8 -*-
"""[W2 - NOTEBOOK] API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAJQs158cnLF2BOnFrDEJnpfaIQsLbrO

# Install Libraries
"""

#!pip install fastapi nest-asyncio uvicorn transformers omegaconf torch

"""# Create Config File"""

yaml_config = """
translate_model: "vinai/vinai-translate-en2vi"
cache_dir: "./models_cache"
"""
with open("config.yaml", "w", encoding="utf-8") as f:
    f.write(yaml_config)

import json

# Tạo CSDL RAG mẫu (knowledge_base.json) cho dự án Smart Tourism
knowledge = {
    "The seafood is fresh": "Hải sản ở đây được đánh bắt trong ngày, rất tươi ngon.",
    "I want to find a traditional museum in Da Nang": "Bảo tàng Điêu khắc Chăm là một lựa chọn tuyệt vời tại Đà Nẵng.",
    "The tour guide was very helpful and friendly": "Hướng dẫn viên của chúng tôi luôn sẵn sàng hỗ trợ và rất thân thiện."
}
with open("knowledge_base.json", "w", encoding="utf-8") as f:
    json.dump(knowledge, f, ensure_ascii=False)

"""# Build Model"""

import torch
from omegaconf import OmegaConf
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

class VinAITranslator:
    def __init__(self, config_path):
        self.config = OmegaConf.load(config_path)
        print("Đang nạp mô hình dịch thuật VinAI...")

        self.tokenizer = AutoTokenizer.from_pretrained(self.config.translate_model, src_lang="en_XX", cache_dir=self.config.cache_dir)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(self.config.translate_model, cache_dir=self.config.cache_dir)

    def __call__(self, en_text):
        inputs = self.tokenizer(en_text, return_tensors="pt", padding=True, truncation=True, max_length=1024)

        with torch.no_grad():
            outputs = self.model.generate(
                **inputs,
                decoder_start_token_id=self.tokenizer.lang_code_to_id["vi_VN"],
                num_return_sequences=1,
                num_beams=5,
                early_stopping=True,
                max_length=1024
            )

        return self.tokenizer.decode(outputs[0], skip_special_tokens=True)

"""# Initialize Model"""

translator = VinAITranslator("./config.yaml")

# Test thử
print(translator("The tour guide was very helpful and friendly."))

"""# Initialize API"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import threading
import uvicorn

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=['*'],
    allow_credentials=True,
    allow_methods=['*'],
    allow_headers=['*'],
)

class TranslationRequest(BaseModel):
    message: str

@app.get('/')
async def root():
    return {"message": "API Dịch Thuật Anh-Việt (VinAI) - Sinh viên: Quang"}

@app.get('/health')
async def health():
    return {"status": "ok", "model": "vinai-translate-en2vi"}

@app.post('/predict')
async def predict(data: TranslationRequest):
    if not data.message or len(data.message.strip()) == 0:
        raise HTTPException(status_code=400, detail="Vui lòng nhập câu tiếng Anh cần dịch!")

    try:
        translated_text = translator(data.message)
        return {
            "original_text": data.message,
            "translated_text": translated_text
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

def run_server():
    uvicorn.run(app, host="0.0.0.0", port=8000)

thread = threading.Thread(target=run_server, daemon=True)
thread.start()

print("Server Translation đã chạy tại cổng 8000")

"""# Call Local API"""

import requests

API_URL = "http://127.0.0.1:8000/predict"
payload = {"message": "I want to find a traditional museum in Da Nang"}

response = requests.post(API_URL, json=payload)
print("Mã trạng thái:", response.status_code)
print("Kết quả JSON:", response.json())

"""# Call Public API"""

import requests

# 1. Dán đường link Pinggy của ông vào đây và thêm đuôi /predict
PUBLIC_API_URL = "https://sgsny-34-125-202-207.run.pinggy-free.link/predict"

# 2. Dữ liệu thử nghiệm số 2 (Đề bài yêu cầu test ít nhất 2 dữ liệu đầu vào)
payload = {"message": "The tour guide was very helpful and friendly"}

# 3. Gọi API
response = requests.post(PUBLIC_API_URL, json=payload)

print("Mã trạng thái:", response.status_code)
print("Kết quả JSON:", response.json())